version: '3.8'

services:
  db:
    image: 'postgres:12-alpine'
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456789
      - POSTGRES_DB=schedule
    volumes:
      - "db-data:/var/lib/postgresql/data"

  app:
    container_name: app
    build: .
    environment:
      - PORT=8080
      - DB_USERNAME=postgres
      - DB_PASSWORD=123456789
      - DB_URL=jdbc:postgresql://db/schedule
      - POSTGRES_DB=schedule
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  db-data: