--create sequence hibernate_sequence start 1 increment 1;
--
--CREATE SCHEMA IF NOT EXISTS schedule
--    AUTHORIZATION postgres;
--
--CREATE TABLE IF NOT EXISTS public.audience
--(
--    id bigint NOT NULL,
--    name character varying(50) NOT NULL,
--    CONSTRAINT audience_pkey PRIMARY KEY (id)
--);
--ALTER TABLE IF EXISTS public.audience
--    OWNER to postgres;
--
--CREATE TABLE IF NOT EXISTS public."group"
--(
--    id bigint NOT NULL,
--    name character varying(50) COLLATE pg_catalog."default" NOT NULL,
--    CONSTRAINT group_pkey PRIMARY KEY (id)
--);
--ALTER TABLE IF EXISTS public."group"
--    OWNER to postgres;
--
